import type { AppState, Unit } from "./econ-types";

const mkUnit = (id: string, floors = 19): Unit => ({
  id,
  capacity: 1600,
  floors,
  currency: "USD",
  brand: "FUJI HITECH",
  model: "MR",
  country: "China",
  kind: "Passenger",
  type: "ელექტრული",
  delivery: "EXW",
  mrType: "MRL",
  specDate: "2026-06-15",
  variant: 1,
  productionWeeks: 8,
  transportWeeks: 13,
  reserveWeeks: 1,
  installWeeks: 9,
  factoryPrice: 18180,
  bankCommission: 50,
  intTransport: 4400,
  terminal: 100,
  localTransport: 350,
  materials: 100,
  otherCost: 0,
  grounding: 180,
  brokerCommission: 0,
});

export const defaultAppState: AppState = {
  project: {
    projectName: "GTB დიდი დიღომი",
    location: "თბილისი",
    buildingType: "საცხოვრებელი კომპლექსი",
    completionYear: 2026,
    units: [mkUnit("L1"), mkUnit("L2")],
    travel: {
      mechanics:    { headcount: 2, days: 30, trips: 1, hotelTotal: 0 },
      electricians: { headcount: 2, days: 10, trips: 1, hotelTotal: 0 },
      admin:        { headcount: 1, days: 10, trips: 4, hotelTotal: 0 },
      distanceKm: 400,
      fuelConsumption: 10,
      workDays: "ორშაბათი – პარასკევი",
    },
  },
  finance: {
    rateDate: "2026-06-15",
    usdRate: 2.6577,
    eurRate: 3.0768,
    vatRate: 0.18,
    incomeTaxRate: 0.20,
    pensionRate: 0.04,
    mealPerDay: 0,
    hotelMechanics: 0,
    hotelElectricians: 0,
    hotelAdmin: 0,
    fuelPricePerL: 0,
    mechRateGel: 280,
    elecRateGel: 80,
    equipmentMarkupPct: 0.03,
    installMarkupPct: 0.50,
    contingencyPct: 0.03,
    fxRiskPct: 0.02,
    warrantyYears: 1,
    warrantyPct: 0,
    monthlyServiceUsd: 0,
    freeServiceMonths: 0,
    guaranteePct: 0,
    guaranteeDays: 0,
    guaranteeAnnualPct: 0,
  },
  payment: {
    procurementAdvancePct: 0.30,
    scenarioA: { name: "სცენარი V1 (25/30/35/10)", tranche1: 0.25, tranche2: 0.30, tranche3: 0.35 },
    scenarioB: { name: "სცენარი V2 (20/30/35/15)", tranche1: 0.20, tranche2: 0.30, tranche3: 0.35 },
  },
};

export const emptyUnit = mkUnit;
