CREATE TABLE public.pipeline_projects (
  id TEXT NOT NULL PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pipeline_projects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pipeline_projects TO anon;
GRANT ALL ON public.pipeline_projects TO service_role;
ALTER TABLE public.pipeline_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow all select" ON public.pipeline_projects FOR SELECT TO public USING (true);
CREATE POLICY "allow all insert" ON public.pipeline_projects FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "allow all update" ON public.pipeline_projects FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "allow all delete" ON public.pipeline_projects FOR DELETE TO public USING (true);

INSERT INTO public.pipeline_projects (id, data) VALUES
('1', '{"name": "სახ. დაცვის სპეც. სამსახური", "contractDate": "2024-03-12", "product": "ლიფტი", "brand": "KLEEMANN", "units": 1, "floors": 4, "contractDuration": 25, "location": "ყვარელი", "currency": "EUR", "kleemannValue": 18274, "hitachiValue": 0, "value": 18274, "revenue": 5262, "tranche1": 35, "deliveryMonth": "აგვისტო", "probability": 100, "comment": "100%", "quarter": "Q1", "manager": "კვარაცხელია თ.", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('2', '{"name": "შპს პეტიტა (2 ობიექტი)", "contractDate": "2024-03-27", "product": "ლიფტი", "brand": "KLEEMANN", "units": 2, "floors": 4, "contractDuration": 16, "location": "თბილისი", "currency": "EUR", "kleemannValue": 25524, "hitachiValue": 0, "value": 25524, "revenue": 7761, "tranche1": 35, "deliveryMonth": "ივლისი", "probability": 100, "comment": "100%", "quarter": "Q1", "manager": "კვარაცხელია თ.", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('3', '{"name": "შპს სითი დეველოპმენტი", "contractDate": "2024-04-18", "product": "ლიფტი", "brand": "KLEEMANN", "units": 3, "floors": 9, "contractDuration": 16, "location": "თბილისი", "currency": "EUR", "kleemannValue": 46522, "hitachiValue": 0, "value": 46522, "revenue": 10560, "tranche1": 50, "deliveryMonth": "აგვისტო", "probability": 100, "comment": "100%", "quarter": "Q2", "manager": "კვარაცხელია თ.", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('4', '{"name": "შპს ჰუალინგი (V3, V4)", "contractDate": "2024-05-15", "product": "ლიფტი", "brand": "KLEEMANN", "units": 2, "floors": 10, "contractDuration": 16, "location": "თბილისი", "currency": "USD", "kleemannValue": 45115, "hitachiValue": 0, "value": 45115, "revenue": 9900, "tranche1": 30, "deliveryMonth": "სექტემბერი", "probability": 100, "comment": "100%", "quarter": "Q2", "manager": "კვარაცხელია თ.", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('5', '{"name": "შპს ტიფლის ჰილს", "contractDate": "2024-07-16", "product": "ლიფტი", "brand": "KLEEMANN", "units": 12, "floors": 2, "contractDuration": 16, "location": "თბილისი", "currency": "USD", "kleemannValue": 257778, "hitachiValue": 0, "value": 257778, "revenue": 34885, "tranche1": 50, "deliveryMonth": "ნოემბერი", "probability": 100, "comment": "100%", "quarter": "Q3", "manager": "კვარაცხელია თ.", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('6', '{"name": "სსიპ საგანმ. ინფრასტრუქ. (ფაზა 2)", "contractDate": "2024-08-01", "product": "ლიფტი", "brand": "KLEEMANN", "units": 2, "floors": 3, "contractDuration": 18, "location": "რეგიონი", "currency": "USD", "kleemannValue": 33261, "hitachiValue": 0, "value": 33261, "revenue": 10000, "tranche1": 30, "deliveryMonth": "დეკემბერი", "probability": 100, "comment": "100%", "quarter": "Q3", "manager": "კვარაცხელია თ.", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('7', '{"name": "შპს სოლო დეველოპმენტ", "contractDate": "2024-09-10", "product": "ლიფტი", "brand": "KLEEMANN", "units": 3, "floors": 12, "contractDuration": 20, "location": "ბათუმი", "currency": "USD", "kleemannValue": 55000, "hitachiValue": 0, "value": 55000, "revenue": 8000, "tranche1": 40, "deliveryMonth": "იანვარი", "probability": 100, "comment": "100%", "quarter": "Q3", "manager": "კვარაცხელია თ.", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('8', '{"name": "შპს მეტროპოლ გრუპ", "contractDate": "2024-11-05", "product": "ესკალატორი", "brand": "HITACHI", "units": 4, "floors": 2, "contractDuration": 24, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 120000, "value": 120000, "revenue": 15000, "tranche1": 30, "deliveryMonth": "მარტი", "probability": 80, "comment": "მოლაპარაკება მიმდინარეობს", "quarter": "Q4", "manager": "კვარაცხელია თ.", "statusDetail": "აქტიური", "status": "პოტ. 60%+"}'::jsonb),
('9', '{"name": "შპს ალიანს სიტი", "contractDate": "2024-12-15", "product": "ლიფტი", "brand": "KLEEMANN", "units": 8, "floors": 45, "contractDuration": 30, "location": "ბათუმი", "currency": "USD", "kleemannValue": 450000, "hitachiValue": 0, "value": 450000, "revenue": 50000, "tranche1": 20, "deliveryMonth": "აპრილი", "probability": 40, "comment": "კონკურენცია მაღალია", "quarter": "Q4", "manager": "კვარაცხელია თ.", "statusDetail": "მოლოდინი", "status": "პოტ. 60%-"}'::jsonb),
('10', '{"name": "შპს გლობალ ბილდინგი", "contractDate": "2024-02-20", "product": "ლიფტი", "brand": "KLEEMANN", "units": 2, "floors": 8, "contractDuration": 16, "location": "ქუთაისი", "currency": "USD", "kleemannValue": 32000, "hitachiValue": 0, "value": 32000, "revenue": 6500, "tranche1": 35, "deliveryMonth": "ივნისი", "probability": 100, "comment": "დასრულებული", "quarter": "Q1", "manager": "ბიგვავა ირაკლი", "statusDetail": "დასრულებული", "status": "დაკონტრაქტებული"}'::jsonb),
('11', '{"name": "შპს ემ კვადრატი", "contractDate": "2024-05-10", "product": "ლიფტი", "brand": "HITACHI", "units": 6, "floors": 22, "contractDuration": 24, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 180000, "value": 180000, "revenue": 22000, "tranche1": 30, "deliveryMonth": "ოქტომბერი", "probability": 100, "comment": "მიმდინარე", "quarter": "Q2", "manager": "ბიგვავა ირაკლი", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('12', '{"name": "შპს არქი", "contractDate": "2024-08-22", "product": "ლიფტი", "brand": "KLEEMANN", "units": 4, "floors": 18, "contractDuration": 20, "location": "თბილისი", "currency": "USD", "kleemannValue": 95000, "hitachiValue": 0, "value": 95000, "revenue": 14000, "tranche1": 40, "deliveryMonth": "იანვარი", "probability": 100, "comment": "მიმდინარე", "quarter": "Q3", "manager": "ბიგვავა ირაკლი", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('13', '{"name": "შპს დომუსი", "contractDate": "2024-10-15", "product": "ლიფტი", "brand": "KLEEMANN", "units": 3, "floors": 10, "contractDuration": 18, "location": "თბილისი", "currency": "USD", "kleemannValue": 60000, "hitachiValue": 0, "value": 60000, "revenue": 9000, "tranche1": 35, "deliveryMonth": "თებერვალი", "probability": 70, "comment": "კონტრაქტის მომზადება", "quarter": "Q4", "manager": "ბიგვავა ირაკლი", "statusDetail": "აქტიური", "status": "პოტ. 60%+"}'::jsonb),
('14', '{"name": "შპს რედკო", "contractDate": "2024-11-20", "product": "ესკალატორი", "brand": "HITACHI", "units": 2, "floors": 2, "contractDuration": 20, "location": "გუდაური", "currency": "USD", "kleemannValue": 0, "hitachiValue": 70000, "value": 70000, "revenue": 10000, "tranche1": 30, "deliveryMonth": "აპრილი", "probability": 30, "comment": "ბიუჯეტის განხილვა", "quarter": "Q4", "manager": "ბიგვავა ირაკლი", "statusDetail": "მოლოდინი", "status": "პოტ. 60%-"}'::jsonb),
('15', '{"name": "შპს თბილისი მოლი", "contractDate": "2024-01-15", "product": "ტრაველატორი", "brand": "HITACHI", "units": 2, "floors": 1, "contractDuration": 24, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 110000, "value": 110000, "revenue": 16000, "tranche1": 30, "deliveryMonth": "მაისი", "probability": 100, "comment": "დასრულებული", "quarter": "Q1", "manager": "ჩიკვაიძე ბექა", "statusDetail": "დასრულებული", "status": "დაკონტრაქტებული"}'::jsonb),
('16', '{"name": "შპს ისთ ფოინთი", "contractDate": "2024-04-20", "product": "ესკალატორი", "brand": "HITACHI", "units": 4, "floors": 2, "contractDuration": 24, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 160000, "value": 160000, "revenue": 24000, "tranche1": 30, "deliveryMonth": "სექტემბერი", "probability": 100, "comment": "მიმდინარე", "quarter": "Q2", "manager": "ჩიკვაიძე ბექა", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('17', '{"name": "შპს გალერია თბილისი", "contractDate": "2024-07-10", "product": "ლიფტი", "brand": "KLEEMANN", "units": 3, "floors": 6, "contractDuration": 18, "location": "თბილისი", "currency": "USD", "kleemannValue": 85000, "hitachiValue": 0, "value": 85000, "revenue": 12000, "tranche1": 40, "deliveryMonth": "დეკემბერი", "probability": 100, "comment": "მიმდინარე", "quarter": "Q3", "manager": "ჩიკვაიძე ბექა", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('18', '{"name": "შპს სითი მოლი", "contractDate": "2024-11-12", "product": "ესკალატორი", "brand": "HITACHI", "units": 6, "floors": 3, "contractDuration": 26, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 250000, "value": 250000, "revenue": 35000, "tranche1": 30, "deliveryMonth": "მაისი", "probability": 65, "comment": "ფასზე მოლაპარაკება", "quarter": "Q4", "manager": "ჩიკვაიძე ბექა", "statusDetail": "აქტიური", "status": "პოტ. 60%+"}'::jsonb),
('19', '{"name": "შპს მეგალაინი", "contractDate": "2024-12-05", "product": "სატვირთო ლიფტი", "brand": "KLEEMANN", "units": 2, "floors": 3, "contractDuration": 16, "location": "თბილისი", "currency": "USD", "kleemannValue": 45000, "hitachiValue": 0, "value": 45000, "revenue": 7000, "tranche1": 35, "deliveryMonth": "აპრილი", "probability": 20, "comment": "შეჩერებული", "quarter": "Q4", "manager": "ჩიკვაიძე ბექა", "statusDetail": "მოლოდინი", "status": "პოტ. 60%-"}'::jsonb),
('20', '{"name": "მთავრობის ადმინისტრაცია", "contractDate": "2024-03-05", "product": "ლიფტი", "brand": "KLEEMANN", "units": 4, "floors": 12, "contractDuration": 20, "location": "თბილისი", "currency": "USD", "kleemannValue": 120000, "hitachiValue": 0, "value": 120000, "revenue": 18000, "tranche1": 50, "deliveryMonth": "აგვისტო", "probability": 100, "comment": "სპეციალური პროექტი", "quarter": "Q1", "manager": "მენეჯმენტი", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('21', '{"name": "საქართველოს ბანკი (სათაო)", "contractDate": "2024-06-15", "product": "ლიფტი", "brand": "HITACHI", "units": 8, "floors": 15, "contractDuration": 24, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 280000, "value": 280000, "revenue": 40000, "tranche1": 40, "deliveryMonth": "ნოემბერი", "probability": 100, "comment": "VIP კლიენტი", "quarter": "Q2", "manager": "მენეჯმენტი", "statusDetail": "წარმოება", "status": "დაკონტრაქტებული"}'::jsonb),
('22', '{"name": "თიბისი ბანკი (სათაო)", "contractDate": "2024-09-05", "product": "ლიფტი", "brand": "HITACHI", "units": 10, "floors": 18, "contractDuration": 28, "location": "თბილისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 350000, "value": 350000, "revenue": 55000, "tranche1": 40, "deliveryMonth": "მარტი", "probability": 100, "comment": "VIP კლიენტი", "quarter": "Q3", "manager": "მენეჯმენტი", "statusDetail": "დადასტურებული", "status": "დაკონტრაქტებული"}'::jsonb),
('23', '{"name": "ბათუმის სტადიონი", "contractDate": "2024-10-20", "product": "ლიფტი", "brand": "KLEEMANN", "units": 6, "floors": 5, "contractDuration": 20, "location": "ბათუმი", "currency": "USD", "kleemannValue": 150000, "hitachiValue": 0, "value": 150000, "revenue": 22000, "tranche1": 50, "deliveryMonth": "აპრილი", "probability": 85, "comment": "ტენდერი", "quarter": "Q4", "manager": "მენეჯმენტი", "statusDetail": "აქტიური", "status": "პოტ. 60%+"}'::jsonb),
('24', '{"name": "ქუთაისის აეროპორტი", "contractDate": "2024-11-25", "product": "ესკალატორი", "brand": "HITACHI", "units": 4, "floors": 2, "contractDuration": 24, "location": "ქუთაისი", "currency": "USD", "kleemannValue": 0, "hitachiValue": 180000, "value": 180000, "revenue": 25000, "tranche1": 30, "deliveryMonth": "მაისი", "probability": 45, "comment": "დაფინანსების მოლოდინი", "quarter": "Q4", "manager": "მენეჯმენტი", "statusDetail": "აქტიური", "status": "პოტ. 60%-"}'::jsonb);